#! /bin/sh
# This script is distributed with Maratona Linux under the terms of GPLv2

PREREQ=""
DESCRIPTION="Maratona fixes..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

#make snap work after reboot
rm -rf /cow/upper/var/lib/snapd

#make sure there is something in icpc home
if [[ ! -d ${rootmnt}/home/icpc ]]; then
  mkdir -p ${rootmnt}/home/icpc
  touch ${rootmnt}/home/icpc/.clean-home
fi

if [[ ! -d ${rootmnt}/home/latam-admin ]]; then
  cp -a ${rootmnt}/rofs/home/latam-admin ${rootmnt}/home/
fi

if grep -q "factoryreset" /proc/cmdline; then
  for i in dev dev/pts sys proc; do
    mount --bind /$i ${rootmnt}/$i
  done
  chroot ${rootmnt} bash /usr/share/maratona-casper/ml-factoryreset.sh
  RET=$?
  if [[ "$RET" == "0" ]]; then
    echo "Removing files..."
    rm -rf /cow/*
    rm -rf ${rootmnt}/home/*
    sleep 1
  fi
  reboot
  while :; do sleep 60; done
fi

if grep -q "mlinstall" /proc/cmdline; then
  for i in dev dev/pts sys proc; do
    mount --bind /$i ${rootmnt}/$i
  done
  chroot ${rootmnt} bash /usr/share/maratona-casper/ml-install.sh
  echo "Please remove Install Media and press ENTER"
  echo "Please remove Install Media and press ENTER"
  echo "Please remove Install Media and press ENTER"
  echo "Please remove Install Media and press ENTER"
  echo "Please remove Install Media and press ENTER"
  echo "Please remove Install Media and press ENTER"
  echo "Please remove Install Media and press ENTER"
  echo "Please remove Install Media and press ENTER"
  echo "Please remove Install Media and press ENTER"
  echo "Please remove Install Media and press ENTER"
  read
  reboot
  while :; do sleep 60; done
fi

if grep -q "mlshell" /proc/cmdline; then
  sh
  echo "Please remove Install Media and press ENTER"
  read
  reboot
  while :; do sleep 60; done
fi
log_end_msg
